export const TITLE_OPTIONS = [
  { value: "Mr", label: "Mr" },
  { value: "Mrs", label: "Mrs" },
  { value: "Ms", label: "Ms" },
  { value: "Miss", label: "Miss" },
  { value: "Dr", label: "Dr" },
];

export const GENDER_OPTIONS = [
  { value: "", label: "Select Gender" },
  { value: "Male", label: "Male" },
  { value: "Female", label: "Female" },
  { value: "Transgender", label: "Transgender" },
];

export const MOTHER_TONGUE_OPTIONS = [
  { value: "", label: "Select Mother Tongue" },
  { value: "Marathi", label: "Marathi" },
  { value: "Hindi", label: "Hindi" },
  { value: "English", label: "English" },
  { value: "Gujarati", label: "Gujarati" },
  { value: "Tamil", label: "Tamil" },
  { value: "Telugu", label: "Telugu" },
  { value: "Kannada", label: "Kannada" },
  { value: "Malayalam", label: "Malayalam" },
  { value: "Bengali", label: "Bengali" },
  { value: "Punjabi", label: "Punjabi" },
  { value: "Other", label: "Other" },
];

export const ADDRESS_TYPE_OPTIONS = [
  { value: "Permanent", label: "Permanent" },
  { value: "Temporary", label: "Temporary" },
];

export const COUNTRIES = [
  { value: "India", label: "India" },
  { value: "Afghanistan", label: "Afghanistan" },
  { value: "Albania", label: "Albania" },
  { value: "Algeria", label: "Algeria" },
  { value: "Argentina", label: "Argentina" },
  { value: "Australia", label: "Australia" },
  { value: "Austria", label: "Austria" },
  { value: "Bahamas", label: "Bahamas" },
  { value: "Bahrain", label: "Bahrain" },
  { value: "Bangladesh", label: "Bangladesh" },
  { value: "Barbados", label: "Barbados" },
  { value: "Belgium", label: "Belgium" },
  { value: "Belize", label: "Belize" },
  { value: "Benin", label: "Benin" },
  { value: "Bhutan", label: "Bhutan" },
  { value: "Bolivia", label: "Bolivia" },
  { value: "Botswana", label: "Botswana" },
  { value: "Brazil", label: "Brazil" },
  { value: "Brunei", label: "Brunei" },
  { value: "Bulgaria", label: "Bulgaria" },
  { value: "Burkina Faso", label: "Burkina Faso" },
  { value: "Burundi", label: "Burundi" },
  { value: "Cambodia", label: "Cambodia" },
  { value: "Cameroon", label: "Cameroon" },
  { value: "Canada", label: "Canada" },
  { value: "Chad", label: "Chad" },
  { value: "Chile", label: "Chile" },
  { value: "China", label: "China" },
  { value: "Colombia", label: "Colombia" },
  { value: "Comoros", label: "Comoros" },
  { value: "Costa Rica", label: "Costa Rica" },
  { value: "Croatia", label: "Croatia" },
  { value: "Cuba", label: "Cuba" },
  { value: "Cyprus", label: "Cyprus" },
  { value: "Czech Republic", label: "Czech Republic" },
  { value: "Denmark", label: "Denmark" },
  { value: "Dominican Republic", label: "Dominican Republic" },
  { value: "Ecuador", label: "Ecuador" },
  { value: "Egypt", label: "Egypt" },
  { value: "El Salvador", label: "El Salvador" },
  { value: "Estonia", label: "Estonia" },
  { value: "Ethiopia", label: "Ethiopia" },
  { value: "Fiji", label: "Fiji" },
  { value: "Finland", label: "Finland" },
  { value: "France", label: "France" },
  { value: "Gabon", label: "Gabon" },
  { value: "Gambia", label: "Gambia" },
  { value: "Germany", label: "Germany" },
  { value: "Ghana", label: "Ghana" },
  { value: "Greece", label: "Greece" },
  { value: "Guatemala", label: "Guatemala" },
  { value: "Guinea", label: "Guinea" },
  { value: "Guyana", label: "Guyana" },
  { value: "Haiti", label: "Haiti" },
  { value: "Honduras", label: "Honduras" },
  { value: "Hungary", label: "Hungary" },
  { value: "Iceland", label: "Iceland" },
  { value: "Indonesia", label: "Indonesia" },
  { value: "Iran", label: "Iran" },
  { value: "Iraq", label: "Iraq" },
  { value: "Ireland", label: "Ireland" },
  { value: "Israel", label: "Israel" },
  { value: "Italy", label: "Italy" },
  { value: "Jamaica", label: "Jamaica" },
  { value: "Japan", label: "Japan" },
  { value: "Jordan", label: "Jordan" },
  { value: "Kazakhstan", label: "Kazakhstan" },
  { value: "Kenya", label: "Kenya" },
  { value: "Kuwait", label: "Kuwait" },
  { value: "Kyrgyzstan", label: "Kyrgyzstan" },
  { value: "Latvia", label: "Latvia" },
  { value: "Lebanon", label: "Lebanon" },
  { value: "Lesotho", label: "Lesotho" },
  { value: "Liberia", label: "Liberia" },
  { value: "Libya", label: "Libya" },
  { value: "Lithuania", label: "Lithuania" },
  { value: "Luxembourg", label: "Luxembourg" },
  { value: "Madagascar", label: "Madagascar" },
  { value: "Malawi", label: "Malawi" },
  { value: "Malaysia", label: "Malaysia" },
  { value: "Maldives", label: "Maldives" },
  { value: "Mali", label: "Mali" },
  { value: "Malta", label: "Malta" },
  { value: "Mauritania", label: "Mauritania" },
  { value: "Mauritius", label: "Mauritius" },
  { value: "Mexico", label: "Mexico" },
  { value: "Moldova", label: "Moldova" },
  { value: "Mongolia", label: "Mongolia" },
  { value: "Montenegro", label: "Montenegro" },
  { value: "Morocco", label: "Morocco" },
  { value: "Mozambique", label: "Mozambique" },
  { value: "Myanmar", label: "Myanmar" },
  { value: "Namibia", label: "Namibia" },
  { value: "Nepal", label: "Nepal" },
  { value: "Netherlands", label: "Netherlands" },
  { value: "New Zealand", label: "New Zealand" },
  { value: "Nicaragua", label: "Nicaragua" },
  { value: "Niger", label: "Niger" },
  { value: "Nigeria", label: "Nigeria" },
  { value: "North Korea", label: "North Korea" },
  { value: "Norway", label: "Norway" },
  { value: "Oman", label: "Oman" },
  { value: "Pakistan", label: "Pakistan" },
  { value: "Panama", label: "Panama" },
  { value: "Papua New Guinea", label: "Papua New Guinea" },
  { value: "Paraguay", label: "Paraguay" },
  { value: "Peru", label: "Peru" },
  { value: "Philippines", label: "Philippines" },
  { value: "Poland", label: "Poland" },
  { value: "Portugal", label: "Portugal" },
  { value: "Qatar", label: "Qatar" },
  { value: "Romania", label: "Romania" },
  { value: "Russia", label: "Russia" },
  { value: "Rwanda", label: "Rwanda" },
  { value: "Saudi Arabia", label: "Saudi Arabia" },
  { value: "Senegal", label: "Senegal" },
  { value: "Serbia", label: "Serbia" },
  { value: "Seychelles", label: "Seychelles" },
  { value: "Sierra Leone", label: "Sierra Leone" },
  { value: "Singapore", label: "Singapore" },
  { value: "Slovakia", label: "Slovakia" },
  { value: "Slovenia", label: "Slovenia" },
  { value: "Somalia", label: "Somalia" },
  { value: "South Africa", label: "South Africa" },
  { value: "South Korea", label: "South Korea" },
  { value: "Spain", label: "Spain" },
  { value: "Sri Lanka", label: "Sri Lanka" },
  { value: "Sudan", label: "Sudan" },
  { value: "Sweden", label: "Sweden" },
  { value: "Switzerland", label: "Switzerland" },
  { value: "Syria", label: "Syria" },
  { value: "Taiwan", label: "Taiwan" },
  { value: "Tajikistan", label: "Tajikistan" },
  { value: "Tanzania", label: "Tanzania" },
  { value: "Thailand", label: "Thailand" },
  { value: "Togo", label: "Togo" },
  { value: "Trinidad and Tobago", label: "Trinidad and Tobago" },
  { value: "Tunisia", label: "Tunisia" },
  { value: "Turkey", label: "Turkey" },
  { value: "Turkmenistan", label: "Turkmenistan" },
  { value: "Uganda", label: "Uganda" },
  { value: "Ukraine", label: "Ukraine" },
  { value: "United Arab Emirates", label: "United Arab Emirates" },
  { value: "United Kingdom", label: "United Kingdom" },
  { value: "United States", label: "United States" },
  { value: "Uruguay", label: "Uruguay" },
  { value: "Uzbekistan", label: "Uzbekistan" },
  { value: "Venezuela", label: "Venezuela" },
  { value: "Vietnam", label: "Vietnam" },
  { value: "Yemen", label: "Yemen" },
  { value: "Zambia", label: "Zambia" },
  { value: "Zimbabwe", label: "Zimbabwe" },
];

export const INDIAN_STATES = [
  { value: "Andhra Pradesh", label: "Andhra Pradesh" },
  { value: "Arunachal Pradesh", label: "Arunachal Pradesh" },
  { value: "Assam", label: "Assam" },
  { value: "Bihar", label: "Bihar" },
  { value: "Chhattisgarh", label: "Chhattisgarh" },
  { value: "Goa", label: "Goa" },
  { value: "Gujarat", label: "Gujarat" },
  { value: "Haryana", label: "Haryana" },
  { value: "Himachal Pradesh", label: "Himachal Pradesh" },
  { value: "Jharkhand", label: "Jharkhand" },
  { value: "Karnataka", label: "Karnataka" },
  { value: "Kerala", label: "Kerala" },
  { value: "Madhya Pradesh", label: "Madhya Pradesh" },
  { value: "Maharashtra", label: "Maharashtra" },
  { value: "Manipur", label: "Manipur" },
  { value: "Meghalaya", label: "Meghalaya" },
  { value: "Mizoram", label: "Mizoram" },
  { value: "Nagaland", label: "Nagaland" },
  { value: "Odisha", label: "Odisha" },
  { value: "Punjab", label: "Punjab" },
  { value: "Rajasthan", label: "Rajasthan" },
  { value: "Sikkim", label: "Sikkim" },
  { value: "Tamil Nadu", label: "Tamil Nadu" },
  { value: "Telangana", label: "Telangana" },
  { value: "Tripura", label: "Tripura" },
  { value: "Uttar Pradesh", label: "Uttar Pradesh" },
  { value: "Uttarakhand", label: "Uttarakhand" },
  { value: "West Bengal", label: "West Bengal" },
  { value: "Delhi", label: "Delhi" },
  { value: "Jammu and Kashmir", label: "Jammu and Kashmir" },
  { value: "Ladakh", label: "Ladakh" },
  { value: "Puducherry", label: "Puducherry" },
  { value: "Chandigarh", label: "Chandigarh" },
  { value: "Andaman and Nicobar Islands", label: "Andaman and Nicobar Islands" },
  { value: "Dadra and Nagar Haveli and Daman and Diu", label: "Dadra and Nagar Haveli and Daman and Diu" },
  { value: "Lakshadweep", label: "Lakshadweep" },
];

export const DISTRICT_OPTIONS: Record<string, { value: string; label: string }[]> = {
  "Maharashtra": [
    { value: "Mumbai City", label: "Mumbai City" },
    { value: "Mumbai Suburban", label: "Mumbai Suburban" },
    { value: "Pune", label: "Pune" },
    { value: "Thane", label: "Thane" },
    { value: "Nagpur", label: "Nagpur" },
    { value: "Nashik", label: "Nashik" },
    { value: "Aurangabad", label: "Aurangabad" },
    { value: "Solapur", label: "Solapur" },
    { value: "Kolhapur", label: "Kolhapur" },
    { value: "Navi Mumbai", label: "Navi Mumbai" },
    { value: "Sangli", label: "Sangli" },
    { value: "Satara", label: "Satara" },
    { value: "Ratnagiri", label: "Ratnagiri" },
    { value: "Sindhudurg", label: "Sindhudurg" },
    { value: "Palghar", label: "Palghar" },
    { value: "Ahmednagar", label: "Ahmednagar" },
    { value: "Beed", label: "Beed" },
    { value: "Nanded", label: "Nanded" },
    { value: "Latur", label: "Latur" },
    { value: "Osmanabad", label: "Osmanabad" },
    { value: "Parbhani", label: "Parbhani" },
    { value: "Jalna", label: "Jalna" },
    { value: "Amravati", label: "Amravati" },
    { value: "Buldhana", label: "Buldhana" },
    { value: "Washim", label: "Washim" },
    { value: "Akola", label: "Akola" },
    { value: "Wardha", label: "Wardha" },
    { value: "Gadchiroli", label: "Gadchiroli" },
    { value: "Chandrapur", label: "Chandrapur" },
    { value: "Gondia", label: "Gondia" },
    { value: "Bhandara", label: "Bhandara" },
  ],
  "Delhi": [
    { value: "Central Delhi", label: "Central Delhi" },
    { value: "East Delhi", label: "East Delhi" },
    { value: "New Delhi", label: "New Delhi" },
    { value: "North Delhi", label: "North Delhi" },
    { value: "North East Delhi", label: "North East Delhi" },
    { value: "North West Delhi", label: "North West Delhi" },
    { value: "Shahdara", label: "Shahdara" },
    { value: "South Delhi", label: "South Delhi" },
    { value: "South East Delhi", label: "South East Delhi" },
    { value: "South West Delhi", label: "South West Delhi" },
    { value: "West Delhi", label: "West Delhi" },
  ],
  "Gujarat": [
    { value: "Ahmedabad", label: "Ahmedabad" },
    { value: "Surat", label: "Surat" },
    { value: "Vadodara", label: "Vadodara" },
    { value: "Rajkot", label: "Rajkot" },
    { value: "Gandhinagar", label: "Gandhinagar" },
    { value: "Bhavnagar", label: "Bhavnagar" },
    { value: "Jamnagar", label: "Jamnagar" },
    { value: "Junagadh", label: "Junagadh" },
    { value: "Kutch", label: "Kutch" },
    { value: "Mehsana", label: "Mehsana" },
    { value: "Patan", label: "Patan" },
    { value: "Banaskantha", label: "Banaskantha" },
    { value: "Sabarkantha", label: "Sabarkantha" },
    { value: "Aravalli", label: "Aravalli" },
    { value: "Kheda", label: "Kheda" },
    { value: "Anand", label: "Anand" },
    { value: "Mahisagar", label: "Mahisagar" },
    { value: "Panchmahal", label: "Panchmahal" },
    { value: "Dahod", label: "Dahod" },
    { value: "Vadodara", label: "Vadodara" },
  ],
  "Karnataka": [
    { value: "Bangalore Urban", label: "Bangalore Urban" },
    { value: "Bangalore Rural", label: "Bangalore Rural" },
    { value: "Mysore", label: "Mysore" },
    { value: "Belgaum", label: "Belgaum" },
    { value: "Hubli-Dharwad", label: "Hubli-Dharwad" },
    { value: "Mangalore", label: "Mangalore" },
    { value: "Belgaum", label: "Belgaum" },
    { value: "Dharwad", label: "Dharwad" },
    { value: "Uttara Kannada", label: "Uttara Kannada" },
    { value: "Dakshina Kannada", label: "Dakshina Kannada" },
    { value: "Udupi", label: "Udupi" },
    { value: "Chitradurga", label: "Chitradurga" },
    { value: "Tumkur", label: "Tumkur" },
    { value: "Chikmagalur", label: "Chikmagalur" },
    { value: "Shimoga", label: "Shimoga" },
    { value: "Hassan", label: "Hassan" },
  ],
  "Tamil Nadu": [
    { value: "Chennai", label: "Chennai" },
    { value: "Coimbatore", label: "Coimbatore" },
    { value: "Madurai", label: "Madurai" },
    { value: "Tiruchirappalli", label: "Tiruchirappalli" },
    { value: "Salem", label: "Salem" },
    { value: "Tiruppur", label: "Tiruppur" },
    { value: "Vellore", label: "Vellore" },
    { value: "Erode", label: "Erode" },
    { value: "Thiruvannamalai", label: "Thiruvannamalai" },
    { value: "Dindigul", label: "Dindigul" },
    { value: "Thanjavur", label: "Thanjavur" },
    { value: "Nagarcoil", label: "Nagarcoil" },
    { value: "Kanchipuram", label: "Kanchipuram" },
    { value: "Tirunelveli", label: "Tirunelveli" },
    { value: "Thoothukudi", label: "Thoothukudi" },
    { value: "Thiruchirappalli", label: "Thiruchirappalli" },
  ],
  "West Bengal": [
    { value: "Kolkata", label: "Kolkata" },
    { value: "Howrah", label: "Howrah" },
    { value: "24 Parganas North", label: "24 Parganas North" },
    { value: "24 Parganas South", label: "24 Parganas South" },
    { value: "Murshidabad", label: "Murshidabad" },
    { value: "Bardhaman", label: "Bardhaman" },
    { value: "Hooghly", label: "Hooghly" },
    { value: "Nadia", label: "Nadia" },
    { value: "Paschim Medinipur", label: "Paschim Medinipur" },
    { value: "Purba Medinipur", label: "Purba Medinipur" },
    { value: "Jalpaiguri", label: "Jalpaiguri" },
    { value: "Darjeeling", label: "Darjeeling" },
    { value: "Birbhum", label: "Birbhum" },
    { value: "Bankura", label: "Bankura" },
    { value: "Purulia", label: "Purulia" },
  ],
  "Uttar Pradesh": [
    { value: "Lucknow", label: "Lucknow" },
    { value: "Ghaziabad", label: "Ghaziabad" },
    { value: "Agra", label: "Agra" },
    { value: "Varanasi", label: "Varanasi" },
    { value: "Prayagraj", label: "Prayagraj" },
    { value: "Kanpur", label: "Kanpur" },
    { value: "Meerut", label: "Meerut" },
    { value: "Aligarh", label: "Aligarh" },
    { value: "Bareilly", label: "Bareilly" },
    { value: "Moradabad", label: "Moradabad" },
    { value: "Saharanpur", label: "Saharanpur" },
    { value: "Gorakhpur", label: "Gorakhpur" },
    { value: "Noida", label: "Noida" },
    { value: "Firozabad", label: "Firozabad" },
    { value: "Jhansi", label: "Jhansi" },
  ],
  "Rajasthan": [
    { value: "Jaipur", label: "Jaipur" },
    { value: "Jodhpur", label: "Jodhpur" },
    { value: "Udaipur", label: "Udaipur" },
    { value: "Bikaner", label: "Bikaner" },
    { value: "Kota", label: "Kota" },
    { value: "Ajmer", label: "Ajmer" },
    { value: "Pilani", label: "Pilani" },
    { value: "Sikar", label: "Sikar" },
    { value: "Bhilwara", label: "Bhilwara" },
    { value: "Alwar", label: "Alwar" },
    { value: "Bharatpur", label: "Bharatpur" },
    { value: "Chittorgarh", label: "Chittorgarh" },
    { value: "Pali", label: "Pali" },
    { value: "Rajsamand", label: "Rajsamand" },
  ],
  "Madhya Pradesh": [
    { value: "Bhopal", label: "Bhopal" },
    { value: "Indore", label: "Indore" },
    { value: "Jabalpur", label: "Jabalpur" },
    { value: "Gwalior", label: "Gwalior" },
    { value: "Ujjain", label: "Ujjain" },
    { value: "Sagar", label: "Sagar" },
    { value: "Dewas", label: "Dewas" },
    { value: "Satna", label: "Satna" },
    { value: "Ratlam", label: "Ratlam" },
    { value: "Rewa", label: "Rewa" },
    { value: "Katni", label: "Katni" },
    { value: "Burhanpur", label: "Burhanpur" },
    { value: "Khandwa", label: "Khandwa" },
    { value: "Chhindwara", label: "Chhindwara" },
  ],
  "Punjab": [
    { value: "Ludhiana", label: "Ludhiana" },
    { value: "Amritsar", label: "Amritsar" },
    { value: "Jalandhar", label: "Jalandhar" },
    { value: "Patiala", label: "Patiala" },
    { value: "Bathinda", label: "Bathinda" },
    { value: "Hoshiarpur", label: "Hoshiarpur" },
    { value: "Sangrur", label: "Sangrur" },
    { value: "Ferozepur", label: "Ferozepur" },
    { value: "Moga", label: "Moga" },
    { value: "Pathankot", label: "Pathankot" },
    { value: "Mohali", label: "Mohali" },
    { value: "Zirakpur", label: "Zirakpur" },
    { value: "Phagwara", label: "Phagwara" },
    { value: "Kapurthala", label: "Kapurthala" },
  ],
  "Telangana": [
    { value: "Hyderabad", label: "Hyderabad" },
    { value: "Warangal", label: "Warangal" },
    { value: "Karimnagar", label: "Karimnagar" },
    { value: "Khammam", label: "Khammam" },
    { value: "Rangareddy", label: "Rangareddy" },
    { value: "Medak", label: "Medak" },
    { value: "Nalgonda", label: "Nalgonda" },
    { value: "Adilabad", label: "Adilabad" },
    { value: "Mahbubnagar", label: "Mahbubnagar" },
    { value: "Siddipet", label: "Siddipet" },
    { value: "Suryapet", label: "Suryapet" },
    { value: "Jagtial", label: "Jagtial" },
  ],
  "Kerala": [
    { value: "Thiruvananthapuram", label: "Thiruvananthapuram" },
    { value: "Kollam", label: "Kollam" },
    { value: "Pathanamthitta", label: "Pathanamthitta" },
    { value: "Alappuzha", label: "Alappuzha" },
    { value: "Kottayam", label: "Kottayam" },
    { value: "Idukki", label: "Idukki" },
    { value: "Ernakulam", label: "Ernakulam" },
    { value: "Thrissur", label: "Thrissur" },
    { value: "Palakkad", label: "Palakkad" },
    { value: "Malappuram", label: "Malappuram" },
    { value: "Kozhikode", label: "Kozhikode" },
    { value: "Wayanad", label: "Wayanad" },
    { value: "Kannur", label: "Kannur" },
    { value: "Kasaragod", label: "Kasaragod" },
  ],
};

export const TALUKA_OPTIONS: Record<string, { value: string; label: string }[]> = {
  "Mumbai City": [
    { value: "South Mumbai", label: "South Mumbai" },
    { value: "Central Mumbai", label: "Central Mumbai" },
    { value: "South Central", label: "South Central" },
    { value: "Western Suburbs", label: "Western Suburbs" },
    { value: "Eastern Suburbs", label: "Eastern Suburbs" },
  ],
  "Pune": [
    { value: "Pune City", label: "Pune City" },
    { value: "Pune Rural", label: "Pune Rural" },
    { value: "Haveli", label: "Haveli" },
    { value: "Mulshi", label: "Mulshi" },
    { value: "Maval", label: "Maval" },
    { value: "Bhor", label: "Bhor" },
    { value: "Velhe", label: "Velhe" },
    { value: "Khed", label: "Khed" },
  ],
  "Thane": [
    { value: "Thane City", label: "Thane City" },
    { value: "Kalyan", label: "Kalyan" },
    { value: "Ulhasnagar", label: "Ulhasnagar" },
    { value: "Ambarnath", label: "Ambarnath" },
    { value: "Bhiwandi", label: "Bhiwandi" },
    { value: "Shahapur", label: "Shahapur" },
    { value: "Vashivli", label: "Vashivli" },
    { value: "Dahanu", label: "Dahanu" },
  ],
  "Nagpur": [
    { value: "Nagpur City", label: "Nagpur City" },
    { value: "Nagpur Rural", label: "Nagpur Rural" },
    { value: "Kamptee", label: "Kamptee" },
    { value: "Hingna", label: "Hingna" },
    { value: "Parseoni", label: "Parseoni" },
    { value: "Umred", label: "Umred" },
  ],
};

export const CITY_OPTIONS: Record<string, { value: string; label: string }[]> = {
  "Maharashtra": [
    { value: "Mumbai", label: "Mumbai" },
    { value: "Pune", label: "Pune" },
    { value: "Nagpur", label: "Nagpur" },
    { value: "Thane", label: "Thane" },
    { value: "Nashik", label: "Nashik" },
    { value: "Aurangabad", label: "Aurangabad" },
    { value: "Solapur", label: "Solapur" },
    { value: "Kolhapur", label: "Kolhapur" },
    { value: "Navi Mumbai", label: "Navi Mumbai" },
    { value: "Sangli", label: "Sangli" },
    { value: "Amravati", label: "Amravati" },
    { value: "Jalgaon", label: "Jalgaon" },
    { value: "Nanded", label: "Nanded" },
    { value: "Latur", label: "Latur" },
    { value: "Dhule", label: "Dhule" },
    { value: "Ahmednagar", label: "Ahmednagar" },
    { value: "Chandrapur", label: "Chandrapur" },
    { value: "Parbhani", label: "Parbhani" },
    { value: "Jalna", label: "Jalna" },
    { value: "Ratnagiri", label: "Ratnagiri" },
    { value: "Satara", label: "Satara" },
    { value: "Wardha", label: "Wardha" },
    {"value": "Gadchiroli", label: "Gadchiroli" },
    { value: "Gondia", label: "Gondia" },
    { value: "Bhandara", label: "Bhandara" },
    { value: "Osmanabad", label: "Osmanabad" },
    { value: "Beed", label: "Beed" },
    { value: "Washim", label: "Washim" },
    { value: "Akola", label: "Akola" },
    { value: "Buldhana", label: "Buldhana" },
  ],
  "Delhi": [
    { value: "New Delhi", label: "New Delhi" },
    { value: "Delhi Cantonment", label: "Delhi Cantonment" },
    { value: "Narela", label: "Narela" },
    { value: "Sultanpuri", label: "Sultanpuri" },
    { value: "Rohini", label: "Rohini" },
    { value: "Dwarka", label: "Dwarka" },
    { value: "Vasant Kunj", label: "Vasant Kunj" },
    { value: "Shahdara", label: "Shahdara" },
  ],
  "Gujarat": [
    { value: "Ahmedabad", label: "Ahmedabad" },
    { value: "Surat", label: "Surat" },
    { value: "Vadodara", label: "Vadodara" },
    { value: "Rajkot", label: "Rajkot" },
    { value: "Gandhinagar", label: "Gandhinagar" },
    { value: "Bhavnagar", label: "Bhavnagar" },
    { value: "Jamnagar", label: "Jamnagar" },
    { value: "Junagadh", label: "Junagadh" },
    { value: "Anand", label: "Anand" },
    { value: "Morbi", label: "Morbi" },
    { value: "Patan", label: "Patan" },
    { value: "Mehsana", label: "Mehsana" },
  ],
  "Karnataka": [
    { value: "Bangalore", label: "Bangalore" },
    { value: "Mysore", label: "Mysore" },
    { value: "Hubli", label: "Hubli" },
    { value: "Mangalore", label: "Mangalore" },
    { value: "Belgaum", label: "Belgaum" },
    { value: "Dharwad", label: "Dharwad" },
    { value: "Bellary", label: "Bellary" },
    { value: "Tumkur", label: "Tumkur" },
    { value: "Shimoga", label: "Shimoga" },
    { value: "Hassan", label: "Hassan" },
    { value: "Chitradurga", label: "Chitradurga" },
    { value: "Udupi", label: "Udupi" },
  ],
  "Tamil Nadu": [
    { value: "Chennai", label: "Chennai" },
    { value: "Coimbatore", label: "Coimbatore" },
    { value: "Madurai", label: "Madurai" },
    { value: "Tiruchirappalli", label: "Tiruchirappalli" },
    { value: "Salem", label: "Salem" },
    { value: "Tiruppur", label: "Tiruppur" },
    { value: "Vellore", label: "Vellore" },
    { value: "Erode", label: "Erode" },
    { value: "Thanjavur", label: "Thanjavur" },
    { value: "Dindigul", label: "Dindigul" },
    { value: "Nagarcoil", label: "Nagarcoil" },
    { value: "Thoothukudi", label: "Thoothukudi" },
    { value: "Tirunelveli", label: "Tirunelveli" },
  ],
  "West Bengal": [
    { value: "Kolkata", label: "Kolkata" },
    { value: "Howrah", label: "Howrah" },
    { value: "Asansol", label: "Asansol" },
    { value: "Siliguri", label: "Siliguri" },
    { value: "Durgapur", label: "Durgapur" },
    { value: "Bardhaman", label: "Bardhaman" },
    { value: "Malda", label: "Malda" },
    { value: "Kharagpur", label: "Kharagpur" },
    { value: "Berhampore", label: "Berhampore" },
    { value: "Habra", label: "Habra" },
    { value: "Haldia", label: "Haldia" },
  ],
  "Uttar Pradesh": [
    { value: "Lucknow", label: "Lucknow" },
    { value: "Ghaziabad", label: "Ghaziabad" },
    { value: "Agra", label: "Agra" },
    { value: "Varanasi", label: "Varanasi" },
    { value: "Prayagraj", label: "Prayagraj" },
    { value: "Kanpur", label: "Kanpur" },
    { value: "Meerut", label: "Meerut" },
    { value: "Aligarh", label: "Aligarh" },
    { value: "Bareilly", label: "Bareilly" },
    { value: "Moradabad", label: "Moradabad" },
    { value: "Saharanpur", label: "Saharanpur" },
    { value: "Gorakhpur", label: "Gorakhpur" },
    { value: "Noida", label: "Noida" },
    { value: "Firozabad", label: "Firozabad" },
    { value: "Jhansi", label: "Jhansi" },
  ],
  "Rajasthan": [
    { value: "Jaipur", label: "Jaipur" },
    { value: "Jodhpur", label: "Jodhpur" },
    { value: "Udaipur", label: "Udaipur" },
    { value: "Bikaner", label: "Bikaner" },
    { value: "Kota", label: "Kota" },
    { value: "Ajmer", label: "Ajmer" },
    { value: "Pilani", label: "Pilani" },
    { value: "Sikar", label: "Sikar" },
    { value: "Bhilwara", label: "Bhilwara" },
    { value: "Alwar", label: "Alwar" },
    { value: "Bharatpur", label: "Bharatpur" },
    { value: "Pali", label: "Pali" },
  ],
};

export const NATIONALITY_OPTIONS = [
  { value: "Indian", label: "Indian" },
  { value: "Other", label: "Other" },
];

export function getDistrictsByState(state: string): { value: string; label: string }[] {
  return DISTRICT_OPTIONS[state] || [];
}

export function getTalukasByDistrict(district: string): { value: string; label: string }[] {
  return TALUKA_OPTIONS[district] || [];
}

export function getCitiesByState(state: string): { value: string; label: string }[] {
  return CITY_OPTIONS[state] || [];
}